# Generated by Django 5.1.7 on 2025-04-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('department', 'year')},
        ),
    ]
