# Generated by Django 5.1.7 on 2025-03-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='slot',
            field=models.CharField(choices=[('A', '8:00 - 9:00'), ('B', '9:00 - 10:00'), ('C', '10:00 - 11:00'), ('D', '11:00 - 12:00'), ('E', '12:00 - 13:00'), ('F', '14:00 - 15:00'), ('G', '15:00 - 16:00'), ('H', '16:00 - 17:00')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'slot')},
        ),
    ]
